<?php $title = "The bookshelf - Admin users" ?>
<?php require 'partials/head.php'; ?>

<body>

  <header class="header">
    <?php require 'partials/navbar.php'; ?>
  </header>

  <div class="container">
    <?php require 'partials/errors.php'; ?>
    <?php require 'partials/notifications.php'; ?>

    <div class="admin-users-wrapper">
      <div class="admin-users-logo">
        <div class="text-left">
          <h3><i class="fas fa-users"></i> Users</h3>
        </div>
      </div>
      <section>
        <div>
          <div class="admin-users-searchbar">
            <form action="admin-users.php" method="post">
              <input type="text" name="user_search" placeholder="Search users...">
              <div class="admin-search-users">
                <button class="btn btn-read" id="admin-searchusers-btn">Search</button>
              </div>
            </form>
          </div>
        </div>
      </section>
    </div>
    

    <section id="posts">

      <div class="admin-users d-flex flex-col justify-center">
        <div class="admin-users-header">
          <h4 class="text-center">Current users</h4>
        </div>
        <table class="text-center admin-table" id="table-admin-users">
          <thead>
            <tr>
              <th>User id</th>
              <th>Role</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Email</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <?php if(!empty($users)) {?>
            <?php foreach($users as $user): ?>
            <tr>
              <td><?= htmlspecialchars($user['id']) ?></td>
              <td><?= htmlspecialchars($user['role']) ?></td>
              <td><?= htmlspecialchars($user['first_name']) ?></td>
              <td><?= htmlspecialchars($user['last_name']) ?></td>
              <td><?= htmlspecialchars($user['email']) ?></td>
              <td>
                <a href="admin-deleteuser.php?id=<?= $user['id'] ?>" class="btn btn-quit">Delete</a>
              </td>
            </tr>
            <?php endforeach; ?>
            <?php  }  ?>
          </tbody>
        </table>
      </div>
    </section>
  </div>
  

  <footer>
    <?php require 'partials/footer.php'; ?>
  </footer>

  <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script  src="assets/js/main.js"></script>

  <?php
        unset($_SESSION['info']);
        unset($_SESSION['error']);
    ?>

</body>

</html>