<?php $title = "The bookshelf - Admin posts" ?>
<?php require 'partials/head.php'; ?>

<body>


  <header class="header">
    <?php require 'partials/navbar.php'; ?>
  </header>

  <div class="container">

    <p><?php require 'partials/notifications.php'; ?></p>
    <p><?php require 'partials/errors.php'; ?></p>
    <div class="admin-posts-wrapper">
      <div class="admin-posts-logo">
        <div class="text-left">
          <h3><i class="fas fa-pencil-alt"></i> Posts</h3>
        </div>
      </div>
      <section>
        <div>
          <div class="admin-posts-searchbar">
            <form action="admin-posts.php" method="post">
              <input type="text" name="post_search" placeholder="Search by keyword">
              <div class="admin-search-posts">
                <button class="btn btn-read" id="admin-searchposts-btn">Search</button>
              </div>
            </form>
          </div>
        </div>

      </section>

      <section id="posts">

        <div class="admin-latest-posts d-flex flex-col justify-center">
          <div class="admin-latest-posts-header">
            <h4 class="text-center">All posts</h4>
          </div>
          <table class="text-center admin-table" id="table-admin-all-posts">
            <thead>
              <tr>
                <th>Post Id</th>
                <th>Title</th>
                <th>Author</th>
                <th>Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <?php if(!empty($posts)) {?>
              <?php foreach($posts as $post): ?>
              <tr>
                <td><?= htmlspecialchars($post['post_id']) ?></td>
                <td><?= htmlspecialchars($post['title']) ?></td>
                <td><?= htmlspecialchars($post['nickname']) ?></td>
                <td><?= date_create($post['created_at'])->format('d/M/Y H:i') ?></td>
                <td>
                  <a href="post-details.php?id=<?= $post['post_id'] ?>" class="btn btn-read">Details</a>
                  <a href="admin-editpost.php?id=<?= $post['post_id'] ?>" class="btn btn-edit">Edit</a>
                  <a href="admin-deletepost.php?id=<?= $post['post_id'] ?>" class="btn btn-quit">Delete</a>
                </td>
              </tr>
              <?php endforeach; ?>
              <?php  } else {?>

              <?php } ?>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div>

  <footer>
    <?php require 'partials/footer.php'; ?>
  </footer>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="assets/js/main.js"></script>

  <?php
        unset($_SESSION['info']);
        unset($_SESSION['error']);
    ?>
</body>

</html>